version: "3"
services:
  front:
    container_name: front
    build: ./front
    ports:
      - "3000:80"
  back:
    container_name: back
    build: ./back
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"